language: node_js

os:
  - linux

node_js:
  - "node"

script:
  - ./build.sh

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: ehaskins.com
  on:
    branch: master
