# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: cd to blog/src
          command: cd blog/src

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build
          command: yarn run build

      - run:
          name: CD to root
          command: cd ../../
      - run:
          name: Copy blog to output folder
          command: cp blog/src/public/* dist -r
      - run:
          name: Copy presentations to output folder
          command: cp presentations/* dist/presentations -r

      # run tests!
      - run: yarn test
